## Legenda
1 - CORRENDO
2 - ANDANDO
3 - CAINDO

### Import das bibliotecas utilizadas

In [19]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

### Seleciona acelX, acelY, acelZ e atividade

In [20]:
df_andando = pd.read_csv("C:\\classificador-de-padroes-de-mobilidade\\dataset\\raw\\Andando-PausasNãoMarcadas.csv")
df_correndo = pd.read_excel("C:\\classificador-de-padroes-de-mobilidade\\dataset\\raw\\Todas_as_Corridas.xlsx")
df_caindo = pd.read_excel("C:\\classificador-de-padroes-de-mobilidade\\dataset\\raw\\Todas_as_Quedas.xlsx")

colunas_selecionadas = ['acelX', 'acelY', 'acelZ', 'idTipoMovimento']

df_andando   = df_andando[colunas_selecionadas]
df_caindo    = df_caindo[colunas_selecionadas]
df_correndo  = df_correndo[colunas_selecionadas]

# Selecionando somente as 500 primeiras linhas de cada dataset
df_andando   = df_andando.head(500)
df_caindo    = df_caindo.head(500)
df_correndo  = df_correndo.head(500)

### Adiciona cálculo da magnitude da aceleração

In [21]:
df_andando['MAGNITUDE_ACEL']   = np.sqrt(df_andando['acelX']**2 + df_andando['acelY']**2 + df_andando['acelZ']**2)
df_caindo['MAGNITUDE_ACEL']    = np.sqrt(df_caindo['acelX']**2 + df_caindo['acelY']**2 + df_caindo['acelZ']**2)
df_correndo['MAGNITUDE_ACEL']  = np.sqrt(df_correndo['acelX']**2 + df_correndo['acelY']**2 + df_correndo['acelZ']**2)


### Concatena e embaralha os datasets

In [22]:
df_completo = pd.concat([df_andando, df_caindo, df_correndo])
df_embaralhado = df_completo.sample(frac=1).reset_index(drop=True)

### Treinamento e teste do modelo

In [23]:
X_train, X_test, y_train, y_test = train_test_split(df_embaralhado[['acelX', 'acelY', 'acelZ']], df_embaralhado['idTipoMovimento'], test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

tree = DecisionTreeClassifier(random_state=42)
tree.fit(X_train, y_train)

y_pred = tree.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[79  2 18]
 [ 3 96  2]
 [22  2 75]]
              precision    recall  f1-score   support

           1       0.76      0.80      0.78        99
           2       0.96      0.95      0.96       101
           3       0.79      0.76      0.77        99

    accuracy                           0.84       299
   macro avg       0.84      0.84      0.84       299
weighted avg       0.84      0.84      0.84       299

